apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: amd64hello-world-hello-world
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: amd64hello-world-hello-world
    app.kubernetes.io/part-of: hello-world
  name: amd64hello-world-hello-world
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: amd64hello-world-hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: amd64hello-world-hello-world
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
