apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: amd64hello-world-hello-world
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: amd64hello-world-hello-world
    app.kubernetes.io/part-of: hello-world
  name: amd64hello-world-hello-world
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: amd64hello-world-hello-world
status:
  loadBalancer: {}
